- id: qmlformat
  name: qmlformat
  description: Format QML files
  entry: qmlformat-qt6 -i
  types: [qml]
  language: system

- id: qmllint
  name: qmllint
  description: Lint QML files
  entry: qmllint-qt6
  types: [qml]
  language: system
