- id: qmlformat
  name: qmlformat
  description: Format QML files
  entry: qmlformat -i
  types: [qml]
  language: system

- id: qmllint
  name: qmllint
  description: Lint QML files
  entry: qmllint
  types: [qml]
  language: system
